# palette = "catppuccin_macchiato"

format = """
$time\
[](bg:#b4befe fg:#fab387)\
$directory\
[](fg:#b4befe bg:#cba6f7)\
$git_branch\
$git_status\
[](fg:#cba6f7 bg:#f5e0dc)\
$rust\
$python\
$conda\
[ ](fg:#f5e0dc)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
#[username]
#show_always = true
#style_user = "bg:#9A348E"


#style_root = "bg:#9A348E"
#format = '[$user ]($style)'
#disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
#[os]
#style = "bg:#9A348E"
#disabled = true # Disabled by default

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
# Sets user-defined palette

# [character]
# # Note the use of Catppuccin color 'maroon'
# success_symbol = "[[♥](green) ❯](maroon)"
# error_symbol = "[❯](red)"
# vicmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bg:#b4befe fg:#313244"
format = "[ $path ]($style)"
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:#cba6f7 fg:#313244"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#cba6f7 fg:#313244"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = ""
style = "bg:#f5e0dc fg:#313244"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#f5e0dc fg:#313244"
format = '[(\($virtualenv\))]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#fab387 fg:#313244"
format = '[ ♥ $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
